GET http://localhost:8080/api/movies
Accept: application/json

###

POST http://localhost:8080/api/movies
Content-Type: application/json

{
  "id": 2,
  "title": "Iron Man",
  "year": 2008,
  "genre": "Action"
}

###


GET http://localhost:8080/api/movies/2
Accept: application/json



###



DELETE http://localhost:8080/api/movies/2
Accept: application/json

###

